# CMS Configurations

system:
  addr: ''
  enable-prometheus-metrics: true
  prometheus-metrics-addr: ''

db:
  db-filename: ''

zap:
  level: ""
  log-dir: ""
  filename: ""
  log-in-console: false
  log-in-rotatefile: false
