apiVersion: v1
kind: Service
metadata:
  name: mihoyo-bbs-genshin-sign-service
spec:
  ports:
  - name: server-http
    port: 5001
    targetPort: 5001
  - name: metrics-http
    port: 9900
    targetPort: 9900
  selector:
    app: mihoyo-bbs-genshin-sign
  type: LoadBalancer
